DATA:
  NUM_CLASS : 2
  CLASS_WEIGHT : [0.006, 1]
  PATCH_SIZE: [3, 64, 64, 64]
  PATCH_MASK: [1, 64, 64, 64]
  SUP_LOSS: False
  DIM_SIZE: 3
  EXTRACTION_STEP : [3, 16, 16, 16]
  EXTRACTION_STEP_MASK : [1, 16, 16, 16]
  CROP_SIZE : [160, 208, 160]

TRAIN:
  DISTINCT_SUBJECT: False
  MASK : "union" # or mask1 and mask2
  BATCH_SIZE : 4
  EPOCHS : 100
  NUM_WORKERS : 4
  PREFETCH_FACTOR : 2
  FOLD: 7
  LOAD_CHECKPOINT: False
  SAVE_TOP_K : 5
  IDX_CHECKPOINT : -1
  WANDB: True
  AUGMENTATION : False
  NORMALIZE : "min_max" # or z_score

SYS:
  ACCELERATOR : "gpu" # or "cpu"
  DEVICES: [0] # list of index gpus
  MIX_PRECISION : 16 # or 32 for normal training

OPT:
  LEARNING_RATE: 0.0001
  FACTOR_LR : 0.5
  PATIENCE_LR : 5

DIRS:
  SAVE_DIR: "./weights_segment3d/"
  PREDICT_DIR: "./predict_testset/"

PREDICT:
  IDX_CHECKPOINT: -1
  BATCH_SIZE: 4
  MIN_SIZE_REMOVE : 15